# Generated by Django 2.1.5 on 2022-03-31 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=True)),
                ('is_societyAdmin', models.BooleanField(default=False)),
                ('university', models.CharField(max_length=40)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=300)),
                ('likes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyAdminUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_societyAdmin', models.BooleanField(default=True)),
                ('is_general', models.BooleanField(default=False)),
                ('society', models.CharField(max_length=40)),
                ('university', models.CharField(max_length=40)),
                ('facebook', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('facebook', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('availability', models.CharField(max_length=100)),
                ('nextEvent', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societysearch.SocietyPage'),
        ),
        migrations.AddField(
            model_name='generaluserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
