# Generated by Django 2.2.26 on 2022-03-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('facebook', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('availability', models.CharField(max_length=100)),
                ('nextEvent', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societysearch.SocietyPage')),
            ],
        ),
    ]
