# Generated by Django 2.2.26 on 2022-03-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societysearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.IntegerField(blank=True),
        ),
    ]
