# Generated by Django 2.1.5 on 2022-03-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societysearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RenameField(
            model_name='generaluserprofile',
            old_name='generalUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='societyadminuserprofile',
            old_name='societyAdminUser',
            new_name='user',
        ),
        migrations.AddField(
            model_name='generaluserprofile',
            name='is_general',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generaluserprofile',
            name='is_societyAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='societyadminuserprofile',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='societyadminuserprofile',
            name='is_societyAdmin',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
