# Generated by Django 2.1.5 on 2022-03-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societysearch', '0002_auto_20220328_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluserprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='generaluserprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='societyadminuserprofile',
            name='username',
        ),
    ]
