# Generated by Django 2.2.26 on 2022-03-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societysearch', '0002_auto_20220323_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
