# Generated by Django 2.1.5 on 2022-03-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societysearch', '0003_auto_20220328_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societyadminuserprofile',
            name='email',
        ),
    ]
